### ISSUE TITLE
Installation as per readme gives error

### ISSUE THREAD

**Issue by erasmuswill** [RiaanBurger/drupal-remix#12]
...
`jquery.cycle downloaded from http://malsup.github.com/jquery.cycle.all.js.                                                                                             [ok]`
`jquery.easing downloaded from http://gsgd.co.uk/sandbox/jquery/easing/jquery.easing.1.3.js.                                                                            [ok]`
`flexslider downloaded from https://github.com/woothemes/FlexSlider/archive/version/2.1.zip.                                                                            [ok]`
`mv: cannot move ‘profiles/remix/libraries’ to ‘sites/all/libraries’: Directory not empty`

**Comment by RiaanBurger** [comment]
Ah, I see Drupal added a README.txt to that folder. Wasn't there before.
Let me push a fix quick.

Mean time, just delete sites/all/libraries then run the last line again:

mv profiles/remix/libraries sites/all/

**Comment by RiaanBurger** [comment]
Updated and pushed with a tank you to you in the commit message:
https://github.com/RiaanBurger/drupal-remix/
